version: '3.4'

services:
  geneticlogi-api:
    image: ${DOCKER_REGISTRY-}geneticlogiapi
    build:
      context: GeneticLogi-API
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    networks:
      - app-network

  geneticlogi-costservice:
    image: ${DOCKER_REGISTRY-}geneticlogicostservice
    build:
      context: GeneticLogi-CostService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    networks:
      - app-network
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: geneticlogi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
