version: '3.9'

services:
  webapi:
    image: geneticlogibackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: geneticlogi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"